# ----------------------------------------------
# АУТЕНТИФИКАЦИЯ
# ----------------------------------------------

# Доступные способы аутентификации. Возможные варианты:
# phone_number – по номеру телефона, через подтверждение смс-кодом.
# Требует обязательную конфигурацию доставки смс в разделе «СМС АВТОРИЗАЦИЯ».
#
# mail – по электронной почте, через пароль и код подтверждения.
# Подтверждение через код по умолчанию включено, отключить можно в разделе «ПОЧТА».
# Требует обязательное заполнение SMTP протоколов в разделе «ПОЧТА».
#
# sso – через SSO провайдер, с помощью корпоративной учетной записи сотрудника.
# Требует обязательную настройку SSO провайдера в разделе «SSO».
#
# Тип данных: массив строк, пример:
# ["phone_number", "mail", "sso"] – аутентификация через номер телефона, почту и SSO
# ["phone_number"] – аутентификация только через номер телефона
# ["mail"] – аутентификация только через почту
# ["sso"] – аутентификация только через SSO
available_methods: ["phone_number", "mail", "sso"]

# ----------------------------------------------
# КАПЧА
# ----------------------------------------------

# Идентификатор проекта Google Recaptcha.
# В документации по подключению Google Recaptcha обозначено как Project ID.
#
# Тип данных: строка
captcha.project_id:

# Общий ключ Google Recaptcha. Данный ключ будет использоваться
# для всех клиентских платформ, кроме тех, для которых задан выделенный ключ.
# В документации по подключению Google Recaptcha обозначено как общий ключ.
#
# Тип данных: строка
captcha.default_client_key:

# Выделенный ключ Google Recaptcha для платформы Android (Google Play).
# Данный ключ будет использоваться только для приложения, установленного через Google Play.
# Использование выделенного ключа для Google Play версии приложения является необходимым требованием.
# В документации по подключению Google Recaptcha обозначено как ключ платформы андроид.
#
# Тип данных: строка
# Пример: captcha.android_client_key: "example_client_key"
captcha.android_client_key:

# Выделенный ключ Google Recaptcha для платформы iOS (Apple Store).
# Данный ключ будет использоваться только для приложения, установленного через AppStore.
# Использование выделенного ключа для AppStore версии приложения является необходимым требованием.
# В документации по подключению Google Recaptcha обозначено как ключ платформы iOS.
#
# Тип данных: строка
# Пример: captcha.ios_client_key: "example_client_key"
captcha.ios_client_key:

# Выделенные ключи клиентских платформ.
# Не являются обязательными, в большинстве случаев их указывать нет необходимости.
#
# Тип данных: строка
# Пример: captcha.huawei_client_key: "example_client_key"
captcha.huawei_client_key:
captcha.electron_client_key:

# Серверный ключ Google Recaptcha.
# Данный ключ используется приложением для идентификации в Google Recaptcha.
# В документации по подключению Google Recaptcha обозначено как серверный ключ.
#
# Тип данных: строка
captcha.server_key:

# Кол-во попыток аутентификации, после которых запрашивается разгадывание капчи.
# При значении = 0 – каждая попытка аутентификации запрашивает разгадывание капчи.
#
# Тип данных: число
captcha.require_after: 2

# ----------------------------------------------
# ПОЧТА
# ----------------------------------------------

# Список доменов почтовых адресов, для которых разрешена аутентификация в приложении.
# Если список пуст, то аутентификация разрешена для всех доменов.
#
# Тип данных: массив строк, пример: ["example.com", "domain.ru"]
mail.allowed_domains: []

# Включена ли опция подтверждения почты при регистрации через проверочный код.
# Требует обязательную конфигурацию доставки email писем в разделе smtp ниже.
#
# Тип данных: булево значение, true\false
mail.registration_2fa_enabled: true

# Включена ли опция подтверждения почты при авторизации через проверочный код.
# Требует обязательную конфигурацию доставки email писем в разделе smtp ниже.
#
# Тип данных: булево значение, true\false
mail.authorization_2fa_enabled: true

# Отправка писем осуществляется по SMTP протоколу.
# Параметры ниже требуют указания SMTP сервера, через который будут доставляться email письма.
#
# Параметры username, password могут быть не заполнены, если SMTP сервер работает без аутентификации.
#
# Тип данных: строка
# Если в поле password используются двойные кавычки необходимо их экранировать, пример: example\"pass
smtp.host:
smtp.port: 465
smtp.username:
smtp.password:

# Тип шифрования соединения. Возможные значения: tls, ssl, пустая строка (если шифрование не требуется).
#
# Тип данных: строка, пример: "ssl"
smtp.encryption:

# Электронный адрес отправителя.
#
# Тип данных: строка, пример: "compass@example.com"
smtp.from:

# ----------------------------------------------
# СМС АВТОРИЗАЦИЯ
# ----------------------------------------------

# Настройки SMS-оператора СМС-Агент.
# Данный оператор является предпочитаемым оператором для рассылки SMS на номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания российских номеров
# необходимо указать префикс "+79", а при обслуживании вообще всех номеров только "+".
#
# Тип данных: массив строк, пример: ["+79"]
sms_agent.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за
# несколькими провайдерами, то система отдаст приоритет тому провайдеру, у
# которого префикс находится в списке приоритетных.
# Логика ввода значений аналогична логике поля provide_phone_code_list.
# Поле не является обязательным для заполнения.
#
# Тип данных: массив строк, пример: ["+79"]
sms_agent.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает
# использоваться для рассылки SMS-сообщений. В большинстве случаев стоит оставить
# небольшой запас, чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
sms_agent.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений.
# Зачастую адрес по умолчанию является актуальными и не требует изменений.
#
# Тип данных: строка
sms_agent.provider_gateway_url: "https://api3.sms-agent.ru/v2.0/"

# Имя приложения, используемого при отправке сообщений.
# Для получателя SMS будет являться отправителем.
#
# Тип данных: строка
sms_agent.app_name:

# Логин, который будет использоваться для авторизации в API SMS-провайдера.
# Логин выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как login.
#
# Тип данных: строка
sms_agent.login:

# Пароль, который будет использоваться для авторизации в API SMS-провайдера.
# Пароль выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как password.
#
# Тип данных: строка
sms_agent.password:



# Настройки SMS-оператора Twilio.
# Данный оператор может отказаться выполнять рассылку на телефонные номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания номеров казахстана
# необходимо указать префиксы "+796" и "+797", для белорусских "+375",
# а при обслуживании вообще всех номеров только "+".
#
# Тип данных: массив строк, пример: ["+796", "+797", "+375"]
twilio.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за
# несколькими провайдерами, то система отдаст приоритет тому провайдеру, у которого
# префикс находится в списке приоритетных.
# Логика ввода значений аналогична логике поля twilio.provide_phone_code_list.
# Поле не является обязательным для заполнения.
#
# Тип данных: массив строк, пример: ["+796", "+797", "+375"]
twilio.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает
# использоваться для рассылки SMS-сообщений. В большинстве случаев стоит оставить
# небольшой запас, чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
twilio.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений.
# Зачастую адрес по умолчанию является актуальными и не требует изменений.
# При использовании оператора Twilio поле является обязательным.
#
# Тип данных: строка
twilio.provider_gateway_url: "https://api.twilio.com/2010-04-01/"

# Уникальное имя отправителя.
# Получатели SMS будут видеть это имя как отправителя сообщения.
# При заполнении данного поля необходимо указать выбранное при подключении провайдера имя.
# В документации подключения провайдера обозначен как Alphanumeric.
#
# Тип данных: строка
twilio.app_name:

# Идентификатор аккаунта, который будет использоваться для авторизации в API SMS-провайдера.
# Идентификатор выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как Account SID.
#
# Тип данных: строка
twilio.account_sid:

# Токен, который будет использоваться для авторизации в API SMS-провайдера.
# Токен выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как Auth Token.
#
# Тип данных: строка
twilio.account_auth_token:



# Настройки SMS-оператора Vonage.
# Данный оператор может отказаться выполнять рассылку на телефонные номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания номеров казахстана необходимо
# указать префиксы "+796" и "+797", для белорусских "+375", а при обслуживании вообще
# всех номеров только "+".
#
# Тип данных: массив строк, пример: ["+796", "+797", "+375"]
vonage.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за несколькими
# провайдерами, то система отдаст приоритет тому провайдеру, у которого префикс находится
# в списке приоритетных.
# Логика ввода значений аналогична логике поля provide_phone_code_list.
# Поле не является обязательным для заполнения.
#
# Тип данных: массив строк, пример: ["+796", "+797"]
vonage.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает использоваться
# для рассылки SMS-сообщений. В большинстве случаев стоит оставить небольшой запас,
# чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
vonage.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений.
# В большинстве случаев адрес по умолчанию является актуальными и не требует изменений.
#
# Тип данных: строка
vonage.provider_gateway_url: "https://rest.nexmo.com/"

# Имя приложения, используемого при отправке сообщений.
# Для получателя SMS будет являться отправителем.
#
# Тип данных: строка
vonage.app_name:

# Ключ, который будет использоваться для авторизации в API SMS-провайдера.
# Ключ выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как API key.
#
# Тип данных: строка
vonage.api_key:

# Секрет, который будет использоваться для авторизации в API SMS-провайдера.
# Секрет выдается при оформлении договора c SMS-провайдером. В документации
# подключения провайдера обозначен как API Secret.
#
# Тип данных: строка
vonage.api_secret:

# ----------------------------------------------
# SSO АВТОРИЗАЦИЯ
# ----------------------------------------------

# ID и секретный ключ клиентского приложения, зарегистрированных в SSO провайдере
#
# Тип данных: строка
sso.client_id:
sso.client_secret:

# Ссылка на метаданные SSO провайдера
#
# Тип данных: строка, пример: "https://example/adfs/.well-known/openid-configuration"
sso.oidc_provider_metadata_link:

# Сопоставление названия атрибутов учетной записи SSO с атрибутами профиля пользователя в Compass.
# Это необходимо для автоматического заполнения информации о пользователе при его регистрации
# через SSO
#
# Поля могут быть пустыми, если атрибут не требуется
# Тип данных: строка
sso.attribution_mapping.first_name: "first_name"
sso.attribution_mapping.last_name: "last_name"
sso.attribution_mapping.mail: "mail"
sso.attribution_mapping.phone_number: "phone_number"

# Кастомизация текста кнопки для запуска аутентификации через SSO на веб-сайте On-Premise решения
#
# Тип данных: строка
sso.web_auth_button_text: "Войти через корп. портал (AD SSO)"

# Включена ли опция альтернативных способов аутентификации при аутентификации через SSO.
# При включенной опции у пользователей прошедших аутентификацию через SSO
# появляется возможность аутентификации через другие способы аутентификации,
# описанных в available_methods в текущем конфигурационном файле.
#
# Тип данных: булево значение, true\false
sso.authorization_alternative_enabled: false
