# ----------------------------------------------
# АУТЕНТИФИКАЦИЯ
# ----------------------------------------------

# Доступные способы аутентификации. Возможные варианты:
# phone_number – по номеру телефона, через подтверждение смс-кодом.
# Требует обязательную конфигурацию доставки смс в разделе «СМС АВТОРИЗАЦИЯ».
#
# mail – по электронной почте, через пароль и код подтверждения.
# Подтверждение через код по умолчанию включено, отключить можно в разделе «ПОЧТА».
# Требует обязательное заполнение SMTP протоколов в разделе «ПОЧТА».
#
# sso – через SSO провайдер, с помощью корпоративной учетной записи сотрудника.
# Требует обязательную настройку SSO провайдера в разделе «SSO».
#
# Тип данных: массив строк, пример:
# ["phone_number", "mail", "sso"] – аутентификация через номер телефона, почту и SSO
# ["phone_number"] – аутентификация только через номер телефона
# ["mail"] – аутентификация только через почту
# ["sso"] – аутентификация только через SSO
available_methods: ["phone_number", "mail", "sso"]

# ----------------------------------------------
# ЗАПРЕТ НА АВТОРИЗАЦИЮ С ПЛАТФОРМ
# ----------------------------------------------

# Запрещено ли пользователям с ПК авторизовываться в приложении.
#
# Тип данных: булево значение, true\false
auth.is_desktop_prohibited: false

# Запрещено ли пользователям с ios авторизовываться в приложении.
#
# Тип данных: булево значение, true\false
auth.is_ios_prohibited: false

# Запрещено ли пользователям с android авторизовываться в приложении.
#
# Тип данных: булево значение, true\false
auth.is_android_prohibited: false

# ----------------------------------------------
# ПОЧТА
# ----------------------------------------------

# Список доменов почтовых адресов, для которых разрешена аутентификация в приложении.
# Если список пуст, то аутентификация разрешена для всех доменов.
#
# Тип данных: массив строк, пример: ["example.com", "domain.ru"]
mail.allowed_domains: []

# Включена ли опция подтверждения почты при регистрации через проверочный код.
# Требует обязательную конфигурацию доставки email писем в разделе smtp ниже.
#
# Тип данных: булево значение, true\false
mail.registration_2fa_enabled: true

# Включена ли опция подтверждения почты при авторизации через проверочный код.
# Требует обязательную конфигурацию доставки email писем в разделе smtp ниже.
#
# Тип данных: булево значение, true\false
mail.authorization_2fa_enabled: true

# Отправка писем осуществляется по SMTP протоколу.
# Параметры ниже требуют указания SMTP сервера, через который будут доставляться email письма.
#
# Параметры username, password могут быть не заполнены, если SMTP сервер работает без аутентификации.
#
# Тип данных: строка
# Если в поле password используются двойные кавычки необходимо их экранировать, пример: example\"pass
smtp.host:
smtp.port: 465
smtp.username:
smtp.password:

# Тип шифрования соединения. Возможные значения: tls, ssl, пустая строка (если шифрование не требуется).
#
# Тип данных: строка, пример: "ssl"
smtp.encryption:

# Электронный адрес отправителя.
#
# Тип данных: строка, пример: "compass@example.com"
smtp.from:

# ----------------------------------------------
# СМС АВТОРИЗАЦИЯ
# ----------------------------------------------

# Настройки SMS-оператора СМС-Агент.
# Данный оператор является предпочитаемым оператором для рассылки SMS на номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания российских номеров
# необходимо указать префикс "+79", а при обслуживании вообще всех номеров только "+".
#
# Тип данных: массив строк, пример: ["+79"]
sms_agent.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за
# несколькими провайдерами, то система отдаст приоритет тому провайдеру, у
# которого префикс находится в списке приоритетных.
# Логика ввода значений аналогична логике поля provide_phone_code_list.
# Поле не является обязательным для заполнения.
#
# Тип данных: массив строк, пример: ["+79"]
sms_agent.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает
# использоваться для рассылки SMS-сообщений. В большинстве случаев стоит оставить
# небольшой запас, чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
sms_agent.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений.
# Зачастую адрес по умолчанию является актуальными и не требует изменений.
#
# Тип данных: строка
sms_agent.provider_gateway_url: "https://api3.sms-agent.ru/v2.0/"

# Имя приложения, используемого при отправке сообщений.
# Для получателя SMS будет являться отправителем.
#
# Тип данных: строка
sms_agent.app_name:

# Логин, который будет использоваться для авторизации в API SMS-провайдера.
# Логин выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как login.
#
# Тип данных: строка
sms_agent.login:

# Пароль, который будет использоваться для авторизации в API SMS-провайдера.
# Пароль выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как password.
#
# Тип данных: строка
sms_agent.password:



# Настройки SMS-оператора Twilio.
# Данный оператор может отказаться выполнять рассылку на телефонные номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания номеров казахстана
# необходимо указать префиксы "+796" и "+797", для белорусских "+375",
# а при обслуживании вообще всех номеров только "+".
#
# Тип данных: массив строк, пример: ["+796", "+797", "+375"]
twilio.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за
# несколькими провайдерами, то система отдаст приоритет тому провайдеру, у которого
# префикс находится в списке приоритетных.
# Логика ввода значений аналогична логике поля twilio.provide_phone_code_list.
# Поле не является обязательным для заполнения.
#
# Тип данных: массив строк, пример: ["+796", "+797", "+375"]
twilio.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает
# использоваться для рассылки SMS-сообщений. В большинстве случаев стоит оставить
# небольшой запас, чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
twilio.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений.
# Зачастую адрес по умолчанию является актуальными и не требует изменений.
# При использовании оператора Twilio поле является обязательным.
#
# Тип данных: строка
twilio.provider_gateway_url: "https://api.twilio.com/2010-04-01/"

# Уникальное имя отправителя.
# Получатели SMS будут видеть это имя как отправителя сообщения.
# При заполнении данного поля необходимо указать выбранное при подключении провайдера имя.
# В документации подключения провайдера обозначен как Alphanumeric.
#
# Тип данных: строка
twilio.app_name:

# Идентификатор аккаунта, который будет использоваться для авторизации в API SMS-провайдера.
# Идентификатор выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как Account SID.
#
# Тип данных: строка
twilio.account_sid:

# Токен, который будет использоваться для авторизации в API SMS-провайдера.
# Токен выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как Auth Token.
#
# Тип данных: строка
twilio.account_auth_token:



# Настройки SMS-оператора Vonage.
# Данный оператор может отказаться выполнять рассылку на телефонные номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания номеров казахстана необходимо
# указать префиксы "+796" и "+797", для белорусских "+375", а при обслуживании вообще
# всех номеров только "+".
#
# Тип данных: массив строк, пример: ["+796", "+797", "+375"]
vonage.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за несколькими
# провайдерами, то система отдаст приоритет тому провайдеру, у которого префикс находится
# в списке приоритетных.
# Логика ввода значений аналогична логике поля provide_phone_code_list.
# Поле не является обязательным для заполнения.
#
# Тип данных: массив строк, пример: ["+796", "+797"]
vonage.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает использоваться
# для рассылки SMS-сообщений. В большинстве случаев стоит оставить небольшой запас,
# чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
vonage.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений.
# В большинстве случаев адрес по умолчанию является актуальными и не требует изменений.
#
# Тип данных: строка
vonage.provider_gateway_url: "https://rest.nexmo.com/"

# Имя приложения, используемого при отправке сообщений.
# Для получателя SMS будет являться отправителем.
#
# Тип данных: строка
vonage.app_name:

# Ключ, который будет использоваться для авторизации в API SMS-провайдера.
# Ключ выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как API key.
#
# Тип данных: строка
vonage.api_key:

# Секрет, который будет использоваться для авторизации в API SMS-провайдера.
# Секрет выдается при оформлении договора c SMS-провайдером. В документации
# подключения провайдера обозначен как API Secret.
#
# Тип данных: строка
vonage.api_secret:

# ----------------------------------------------
# SSO АВТОРИЗАЦИЯ
# ----------------------------------------------

# Укажите протокол, который будет использоваться для аутентификации. Возможные варианты:
# "oidc" – протокол OpenID Connect
# "ldap" – протокол Lightweight Directory Access Protocol
#
# Тип данных: строка
sso.protocol: ""

# Кастомизация текста кнопки для запуска аутентификации через SSO на веб-сайте On-Premise решения
#
# Тип данных: строка
sso.web_auth_button_text: "Войти через корп. портал (SSO LDAP)"

# Включена ли опция альтернативных способов аутентификации при аутентификации через SSO.
# При включенной опции у пользователей прошедших аутентификацию через SSO
# появляется возможность аутентификации через другие способы аутентификации,
# описанных в available_methods в текущем конфигурационном файле.
#
# Тип данных: булево значение, true\false
sso.authorization_alternative_enabled: false

# Включена ли опция актуализации Имени Фамилии пользователей в Compass каждый раз, когда они успешно авторизуются
# в приложении через SSO.
#
# Тип данных: булево значение, true\false
sso.full_name_actualization_enabled: true

# Автоматическое вступление пользователей после регистрации через SSO/LDAP в первую команду на сервере.
# От лица администратора будет создана бессрочная ссылка-приглашение с заданным параметром вступления в команду.
# Параметр принимает следующие значения:
# member – пользователи автоматически вступают как участники;
# guest – пользователи автоматически вступают как гости;
# moderation – отправляется заявка на вступление в команду, требующая подтверждение от администратора;
# disabled – опция автоматического вступления в первую команду выключена.
#
# Тип данных: строка
sso.auto_join_to_team: "member"

# ----------------------------------------------
# SSO АВТОРИЗАЦИЯ ПО ПРОТОКОЛУ OIDC (OPENID CONNECT)
# ----------------------------------------------

# ID и секретный ключ клиентского приложения, зарегистрированных в SSO провайдере
#
# Тип данных: строка
oidc.client_id:
oidc.client_secret:

# Ссылка на метаданные SSO провайдера
#
# Тип данных: строка, пример: "https://example/adfs/.well-known/openid-configuration"
oidc.oidc_provider_metadata_link:

# Сопоставление названия атрибутов учетной записи SSO с атрибутами профиля пользователя в Compass.
# Это необходимо для автоматического заполнения информации о пользователе при его регистрации
# через SSO
#
# Поля могут быть пустыми, если атрибут не требуется
# Тип данных: строка
oidc.attribution_mapping.first_name: "first_name"
oidc.attribution_mapping.last_name: "last_name"
oidc.attribution_mapping.mail: "mail"
oidc.attribution_mapping.phone_number: "phone_number"

# ----------------------------------------------
# SSO АВТОРИЗАЦИЯ ПО ПРОТОКОЛУ LDAP
# ----------------------------------------------

# Хост сервера LDAP.
#
# Тип данных: строка, пример: "example.com"
ldap.server_host:

# Порт сервера LDAP.
#
# Тип данных: число, пример: 636
ldap.server_port: 636

# Контекст поиска пользователей в LDAP каталоге.
#
# Тип данных: строка, пример: "ou=users,dc=example,dc=com"
ldap.user_search_base:

# Название атрибута учетной записи LDAP, значение которого будет использоваться в качестве username в форме авторизации
# Значение этого атрибута должно быть уникальным для каждой учетной записи
#
# Тип данных: строка, пример:
# Для Active Directory – "sAMAccountName"
# Для FreeIPA – "uid"
ldap.user_unique_attribute:

# Лимит неудачных попыток аутентификации, по достижению которых IP адрес пользователя получает блокировку на 15 минут.
#
# Тип данных: число
ldap.limit_of_incorrect_auth_attempts: 5

# Включен ли мониторинг удаления / блокировки учетной записи LDAP для запуска автоматической
# блокировки связанного пользователя в Compass.
#
# Тип данных: булево значение, пример: true\false
ldap.account_disabling_monitoring_enabled: false

# Уровень автоматической блокировки при отключении учетной записи LDAP, связанной с пользователем Compass.
# Обязателен к заполнению в случае включенного параметра ldap.account_disabling_monitoring_enabled
# Возможные уровни:
# "light" – у связанного пользователя Compass закрываются все активные сессии, блокируется доступ к пространствам на вашем сервере.
# "hard"  – у связанного пользователя Compass закрываются все активные сессии, блокируется доступ к пространствам на вашем сервере,
#           пользователь покидает все команды.
ldap.on_account_disabling: "light"

# Уровень автоматической блокировки при полном удалении учетной записи LDAP, связанной с пользователем Compass.
# Обязателен к заполнению в случае включенного параметра ldap.account_disabling_monitoring_enabled
# Возможные уровни:
# "light" – у связанного пользователя Compass закрываются все активные сессии, блокируется доступ к пространствам на вашем сервере.
# "hard"  – у связанного пользователя Compass закрываются все активные сессии, блокируется доступ к пространствам на вашем сервере,
#           пользователь покидает все команды.
# Если использовались почта или номер телефона для авторизации одновременно с LDAP, то в случае удаления учетной записи в LDAP,
# привязанная почта и номер пользователя станут недоступны для повторной регистрации/авторизации.
ldap.on_account_removing: "light"

# Полный DN (Distinguished Name) учетной записи LDAP, которая будет использоваться
# для поиска других учетных записей и мониторинга их удаления/блокировки в каталоге.
# Обязателен к заполнению в случае включенного параметра ldap.account_disabling_monitoring_enabled
# Рекомендовано к заполнению в случае использования LDAP провайдера Active Directory
#
# Тип данных: строка, пример: "uid=compass_monitor,ou=users,dc=example,dc=com"
ldap.user_search_account_dn:

# Пароль учетной записи LDAP, которая будет использоваться
# для поиска других учетных записей и мониторинга их удаления/блокировки в каталоге.
# Обязателен к заполнению в случае включенного параметра ldap.account_disabling_monitoring_enabled
# Рекомендовано к заполнению в случае использования LDAP провайдера Active Directory
#
# Тип данных: строка, пример: "qwerty12345"
ldap.user_search_account_password:

# Временной интервал между проверками мониторинга блокировки пользователя LDAP.
# Обязателен к заполнению в случае включенного параметра ldap.account_disabling_monitoring_enabled
#
# Тип данных: строка формата:
# Ns – интервал каждые N секунд
# Nm – интервал каждые N минут
# Nh – интервал каждые N часов
# Пример: 5m – интервал каждые 5 минут
ldap.account_disabling_monitoring_interval: "5m"

# Количество подгружаемых учетных записей из LDAP за один запрос в механизме мониторинга удаления / блокировки учетной записи LDAP
# Обязателен к заполнению в случае включенного параметра ldap.account_disabling_monitoring_enabled
# Зачастую подходит значение по умолчанию, если в настройках LDAP-провайдера не было установлено ограничение ниже текущего значения
#
# Тип данных: число
ldap.user_search_page_size: 1000
