# ----------------------------------------------
# КАПЧА
# ----------------------------------------------

# Включена ли опция проверки капчи при достижении лимита попыток аутентификации.
#
# Тип данных: булево значение, true\false
captcha.enabled: true

# Кол-во попыток аутентификации, после которых запрашивается разгадывание капчи.
# При значении = 0 – каждая попытка аутентификации запрашивает разгадывание капчи.
#
# Тип данных: число
captcha.require_after: 2

# ----------------------------------------------
# Google Recaptcha
# ----------------------------------------------

# Идентификатор проекта Google Recaptcha.
# В документации по подключению Google Recaptcha обозначено как Project ID.
#
# Тип данных: строка
google_captcha.project_id:

# Общий ключ Google Recaptcha. Данный ключ будет использоваться
# для всех клиентских платформ, кроме тех, для которых задан выделенный ключ.
# В документации по подключению Google Recaptcha обозначено как общий ключ.
#
# Тип данных: строка
google_captcha.default_client_key:

# Выделенный ключ Google Recaptcha для платформы Android (Google Play).
# Данный ключ будет использоваться только для приложения, установленного через Google Play.
# Использование выделенного ключа для Google Play версии приложения является необходимым требованием.
# В документации по подключению Google Recaptcha обозначено как ключ платформы андроид.
#
# Тип данных: строка
# Пример: captcha.android_client_key: "example_client_key"
google_captcha.android_client_key:

# Выделенный ключ Google Recaptcha для платформы iOS (Apple Store).
# Данный ключ будет использоваться только для приложения, установленного через AppStore.
# Использование выделенного ключа для AppStore версии приложения является необходимым требованием.
# В документации по подключению Google Recaptcha обозначено как ключ платформы iOS.
#
# Тип данных: строка
# Пример: captcha.ios_client_key: "example_client_key"
google_captcha.ios_client_key:

# Выделенные ключи клиентских платформ.
# Не являются обязательными, в большинстве случаев их указывать нет необходимости.
#
# Тип данных: строка
# Пример: captcha.huawei_client_key: "example_client_key"
google_captcha.huawei_client_key:
google_captcha.electron_client_key:

# Серверный ключ Google Recaptcha.
# Данный ключ используется приложением для идентификации в Google Recaptcha.
# В документации по подключению Google Recaptcha обозначено как серверный ключ.
#
# Тип данных: строка
google_captcha.server_key:

# ----------------------------------------------
# Yandex SmartCaptcha
# ----------------------------------------------

# Клиентский ключ Yandex SmartCaptcha. Данный ключ будет использоваться
# для всех клиентских платформ.
# В документации по подключению Yandex SmartCaptcha обозначено как ключ клиента.
#
# Тип данных: строка
yandex_captcha.default_client_key:

# Серверный ключ Yandex SmartCaptcha.
# Данный ключ используется приложением для идентификации в Yandex SmartCaptcha.
# В документации по подключению Yandex SmartCaptcha обозначено как ключ сервера.
#
# Тип данных: строка
yandex_captcha.server_key:
