# Флаг включения Google Recaptcha, возможные значения: 1 — включена, 0 — выключена.
# Если Google Recaptcha включена, то поля default_client_key, android.client_key и server_key должны быть заданы.
#
# Тип данных: число
# Пример: is_enabled: 0
is_enabled: 0

# Общий ключ Google Recaptcha. Данный ключ будет использоваться
# для всех клиентских платформ, кроме тех, для которых задан выделенный ключ.
# В документации по подключению Google Recaptcha обозначено как общий ключ.
#
# Тип данных: строка
# Пример: default_client_key: example_default_client_key
default_client_key:

# Выделенный ключ Google Recaptcha для платформы Android (Google Play).
# Данный ключ будет использоваться только для приложения, установленного через Google Play
# Использование выделенного ключа для Google Play версии приложения является необходимым требованием.
# В документации по подключению Google Recaptcha обозначено как ключ платформы андроид.
#
# Тип данных: строка
# Пример: android.client_key: example_client_key
android.client_key:

# Выделенные ключи клиентских платформ.
# Не являются обязательными, в большинстве случаев их указывать нет необходимости.
#
# Тип данных: строка
# Пример: ios.client_key: example_client_key
ios.client_key:
huawei.client_key:
electron.client_key:

# Серверный ключ Google Recaptcha.
# Данный ключ используется приложение для идентификации в системе Google Recaptcha.
# В документации по подключению Google Recaptcha обозначено как серверный ключ.
#
# Тип данных: строка
# Пример: server_key: example_server_key
server_key:
