# Параметры подключения к базам данных.
#
# Compass On-premise может работать в двух режимах:
#   — docker — приложение само создает нужные БД в соответствии с конфигурацией;
#   — host — приложение используется БД, которые предоставляет пользователь.
#
# По умолчанию используется режим docker, рекомендуемый для большинства случаев.
# Если режим docker не удовлетворяет требованиям, то с помощью настроек ниже можно
# задать конфигурацию собственных заранее запущенных БД.
database_connection:

  ################################################################################
  # Настройки по умолчанию (docker).
  # Блок ниже нужно закомментировать, если будет использоваться режим работы host.
  ################################################################################
  driver: "docker"
  driver_data: {}

  #################################################################################
  # Настройки режима host.
  # Блок ниже нужно раскомментировать, если будет использоваться режим работы host.
  #################################################################################
  # driver: "host"
  # driver_data:
  #   # Системная база данных. Хранит в себе информацию данные учетных записей,
  #   # данные системных файлов и файлов по умолчанию, сервисные данные команд,
  #   # сервисные данные ВКС и системную информацию
  #   project_mysql_hosts:
  #     monolith:
  #       host: ""
  #       port:
  #       root_password: ""
  #   # Базы данных команд. Каждой команде необходимо выделить собственную БД.
  #   # Хранит в себе данные переписок, данные карточек сотрудников и данные
  #   # пользовательских файлов.
  #   company_mysql_hosts:
  #     # Блок параметров для команды
  #     - host: ""
  #       port:
  #       root_password: ""
  #     # Если нужно развернуть более одной команды, необходимо добавить
  #     # дополнительные блоки для БД команды, скопировав строки ниже.
  #     # Обратите внимание на форматирование, все блоки должны иметь
  #     # одинаковый отступ (стандартная yaml-разметка для массива).
  #     # - host: ""
  #     #   port:
  #     #   root_password: ""