# ----------------------------------------------
# НАСТРОЙКИ ДЛЯ ИНТЕГРАЦИИ С DLP СИСТЕМОЙ
# ----------------------------------------------

# Compass может работать с внешним ICAP сервером, предоставляемым DLP системой.
# При активной настройке все сообщения и файлы будут передаваться на проверку в DLP систему перед отправкой и редактированием.
# Настройка правил для ICAP сервера производится на стороне DLP системы
# Если интеграция с DLP включена, но ICAP сервер недоступен, то ни одно сообщение или файл не будут отправлены
# На данный момент на ICAP сервер отправляются только REQMOD запросы

# Включена ли отправка сообщений и файлов на проверку на ICAP сервера
#
# Тип данных: булево значение, true\false
icap.is_enabled: false

# Адрес сервера ICAP
#
# Тип данных: строка
icap.host: ""

# Порт на сервере, который слушает ICAP сервер
#
# Тип данных: число
icap.port: 1344

# Путь до сервера ICAP. Необходим, если ICAP сервер доступен по определенному пути на сервере.
# При указании сервиса, Compass будет обращаться по следующему адресу - {icap.host}:{icap.port}/{icap.url_path}
# В большинстве случаев остается пустым
#
# Тип данных: строка
icap.url_path: ""

# Сущности, которые нужно отправлять на проверку в сервер ICAP
# Возможные значения для добавления
# - text - текстовые сообщения, отправляемые в чат или тред
# - file - файлы, загружаемые в приложение
#
# Значения перечисляются через запятую
#
# Тип данных: строка
# Пример: "text, file"
icap.control_entity_list: "text, file"

# Расширения файлов, которые необходимо отправлять на проверку в DLP систему.
# Заполняется, если выбрана отправка файлов в DLP. Если список пуст, в DLP отправляются файлы с любыми расширениями.
#
# Значения перечисляются через запятую
#
# Тип данных: строка
# Пример "doc, pdf"
icap.file_extension_list: ""