# Имя сертификата для домена с доверенной подписью.
# Файл сертификата должен находиться в директории /etc/nginx/ssl.
#
# Тип данных: строка
# Пример: nginx.ssl_crt: "certificate.crt"
nginx.ssl_crt:

# Имя ключа сертификата для домена с доверенной подписью.
# Файл ключ должен находиться в директории /etc/nginx/ssl.
#
# Тип данных: строка
# Пример: nginx.ssl_key: "private.key"
nginx.ssl_key:

# IPv4 адрес сервера, на котором выполняется установка приложения. Внутренний трафик приложения
# будет пересылаться по этом адресу. Не используйте адрес 127.0.0.1, localhost и другие замыкающие адреса.
#
# Тип данных: строка
# Пример: host_ip: "10.11.92.8"
host_ip:

# Доменное имя, которое будет использоваться для доступа к приложению.
# Доменное имя должно быть доступно из внешней сети.
#
# Тип данных: строка
# Пример: domain: "example_domain"
domain:

# Директория, где приложение будет хранить свои постоянные данные.
# Указываемая директория должна существовать и быть доступной для записи.
#
# Тип данных: строка
# Пример: root_mount_path: "/home/compass"
root_mount_path:

# Внешний порт для контейнера с сайтом авторизации. Внутренний трафик сайта
# будет пересылаться на этот порт.
#
# Тип данных: число
# Пример: join_web.service.join_web.external_port: 31900
join_web.service.join_web.external_port: 31900

# Внешний порт для контейнера с nginx. Внутренний трафик приложения
# будет пересылаться на этот порт.
#
# Тип данных: число
# Пример: monolith_nginx_port: 32100
monolith_nginx_port: 32100

# Внешний порт для контейнера с микросервисом управления MySQL пространств.
# Запросы к микросервису будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: domino.go_database_controller_port: 31101
domino.go_database_controller_port: 31101

# Внешний порт для контейнера с manticore-search для полнотекстового поиска в приложении.
# Запросы к manticore будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: domino.service.manticore.external_port: 31102
domino.service.manticore.external_port: 31102

# Внешний порт для доступа к сервису звонков.
# Запросы к janus будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: janus.service.janus.port: 31801
janus.service.janus.port: 31801

# Внешний порт для доступа к админ-панели звонков.
# Запросы к админ-панели звонков будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: janus.service.janus.admin_port: 31802
janus.service.janus.admin_port: 31802

# Начальный порт для передачи мультимедиа-данных звонков в приложении.
# Порты начиная с этого будут выделены под RTP соединения звонков.
#
# Тип данных: число
# Пример: janus.service.janus.rtp_port_from: 33000
janus.service.janus.rtp_port_from: 33000

# Конечный порт для передачи мультимедиа-данных звонков в приложении.
# Порты заканчивая этим будут выделены под RTP соединения звонков.
#
# Тип данных: число
# Пример: janus.service.janus.rtp_port_to: 33999
janus.service.janus.rtp_port_to: 33999

# Внешний порт для подключения к TURN серверу звонков.
# Внешние запросы к TURN серверу звонков будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: janus.service.coturn.external_port: 3478
janus.service.coturn.external_port: 3478

# Внешний порт для защищенного подключения к TURN серверу звонков.
# Внешние запросы к TURN серверу звонков будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: janus.service.coturn.external_tls_port: 5349
janus.service.coturn.external_tls_port: 5349

# Начальный порт для клиентских соединений звонков в приложении.
# Порты начиная с этого будут выделены под клиентские соединения к TURN серверу звонков.
#
# Тип данных: число
# Пример: janus.service.coturn.exchange_port_from: 34000
janus.service.coturn.exchange_port_from: 34000

# Конечный порт для клиентских соединений звонков в приложении.
# Порты заканчивая этим будут выделены под клиентские соединения к TURN серверу звонков.
#
# Тип данных: число
# Пример: janus.service.coturn.exchange_port_to: 34999
janus.service.coturn.exchange_port_to: 34999

# Внешний порт для контейнера с nginx звонков. Внутренний трафик звонков
# будет пересылаться на этот порт.
#
# Тип данных: число
# Пример: janus.service.nginx.external_https_port: 31800
janus.service.nginx.external_https_port: 31800

# Начальный порт для MySQL созданных пространств в приложении.
# Порты начиная с этого будут выделены под MySQL пространств в приложении.
#
# Тип данных: число
# Пример: company.start_port: 35150
company.start_port: 35150

# Конечный порт для MySQL созданных пространств в приложении.
# Порты заканчивая этим будут выделены под MySQL пространств в приложении.
#
# Тип данных: число
# Пример: company.end_port: 35165
company.end_port: 35165