# Имя сертификата для домена с доверенной подписью.
# Файл сертификата должен находиться в директории /etc/nginx/ssl.
#
# Тип данных: строка
# Пример: nginx.ssl_crt: "certificate.crt"
nginx.ssl_crt:

# Имя ключа сертификата для домена с доверенной подписью.
# Файл ключ должен находиться в директории /etc/nginx/ssl.
#
# Тип данных: строка
# Пример: nginx.ssl_key: "private.key"
nginx.ssl_key:

# IPv4 адрес сервера, на котором выполняется установка приложения. Внутренний трафик приложения
# будет пересылаться по этом адресу. Не используйте адрес 127.0.0.1, localhost и другие замыкающие адреса.
#
# Тип данных: строка
# Пример: host_ip: "10.11.92.8"
host_ip:

# Доменное имя, которое будет использоваться для доступа к приложению.
# Доменное имя должно быть доступно из внешней сети.
#
# Тип данных: строка
# Пример: domain: "example_domain"
domain:

# Директория, где приложение будет хранить свои постоянные данные.
# Указываемая директория должна существовать и быть доступной для записи.
#
# Тип данных: строка
# Пример: root_mount_path: "/home/compass"
root_mount_path:

# Внешний порт для контейнера с сайтом авторизации. Внутренний трафик сайта
# будет пересылаться на этот порт.
#
# Тип данных: число
# Пример: join_web.service.join_web.external_port: 31900
join_web.service.join_web.external_port: 31900

# Внешний порт для контейнера с сайтом вкс страницы, перед присоединением к конференции.
# Внутренний трафик сайта будет пересылаться на этот порт.
#
# Тип данных: число
# Пример: jitsi_web.service.jitsi_web.external_port: 31901
jitsi_web.service.jitsi_web.external_port: 31901

# Внешний порт для контейнера с nginx. Внутренний трафик приложения
# будет пересылаться на этот порт.
#
# Тип данных: число
# Пример: monolith_nginx_port: 32100
monolith_nginx_port: 32100

# Внешний порт для контейнера с микросервисом управления MySQL пространств.
# Запросы к микросервису будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: domino.go_database_controller_port: 31101
domino.go_database_controller_port: 31101

# Внешний порт для контейнера с manticore-search для полнотекстового поиска в приложении.
# Запросы к manticore будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: domino.service.manticore.external_port: 31102
domino.service.manticore.external_port: 31102

# Порт для https запросов к веб-интерфейсу Jitsi.
# Запросы к веб-интерфейсу будут пересылаться на этот порт.
#
# Тип данных: число
# Пример: jitsi.service.web.https_port: 35000
jitsi.service.web.https_port: 35000

# Порт для передачи мультимедиа-данных конференции в приложении.
# Порт будет выделен под RTP соединения участников в конференции.
#
# Тип данных: число
# Пример: jitsi.service.jvb.media_port: 10000
jitsi.service.jvb.media_port: 10000

# Необязательный параметр. Используйте его для указания IP-адреса или списка IP-адресов (через запятую),
# по которым клиенты будут подключаться к вашему медиа-серверу Compass On-Premise.
# Этот параметр особенно полезен, если сервер находится за NAT. В этом случае укажите публичный IP-адрес,
# а затем через запятую — IP-адрес, указанный в параметре `host_ip` выше.
#
# Тип данных: строка
# Пример: jitsi.service.jvb.media_advertise_ips: "212.41.12.120,10.0.1.5"
jitsi.service.jvb.media_advertise_ips: ""

# Порт для компонента jicofo, модуля для ВКС
# Запросы к компоненту будут отправлять на этот порт.
#
# Тип данных: число
# Пример: jitsi.service.jicofo.port: 35001
jitsi.service.jicofo.port: 35001

# Порт для компонента prosody, модуля для ВКС
# Запросы к компоненту будут отправлять на этот порт.
#
# Тип данных: число
# Пример: jitsi.service.prosody.port: 35002
jitsi.service.prosody.serve_port: 35002

# Адрес TURN сервера, который будет использоваться для соединения в ВКС
# По умолчанию указан публичный TURN сервер Compass
#
# Тип данных: строка
# Пример: jitsi.service.turn.host: "onpremise-turn.getcompass.ru"
jitsi.service.turn.host: "onpremise-turn.getcompass.ru"

# Порт TURN сервера, который принимает входящие UDP/TCP соединения клиентов
# По умолчанию указан порт от публичного TURN сервера Compass
#
# Тип данных: число
# Пример: jitsi.service.turn.port: 80
jitsi.service.turn.port: 80

# Порт TURN сервера, который принимает входящие соединения клиентов, использующие протокол TLS
# По умолчанию указан порт от публичного TURN сервера Compass
#
# Тип данных: число
# Пример: jitsi.service.turn.tls_port: 443
jitsi.service.turn.tls_port: 443

# Секретный ключ TURN сервера
# По умолчанию указан секретный ключ публичного TURN сервера Compass
#
# Тип данных: строка
# Пример: jitsi.service.turn.secret: "secret-key"
jitsi.service.turn.secret: "XKwpb9C2bMkhNCsWxxg2CxzGDrl3wZG6"

# Список используемых протоколов для соединения клиентов с TURN сервером
# По умолчанию используется только UDP протокол для повышения качества
# видеоконференций в нестабильных сетях
#
# Тип данных: массив строк, пример:
# ["udp"] – используется только UDP протокол
# ["tcp"] – используется только TCP протокол
# ["udp", "tcp"] – используются оба протокола
jitsi.service.turn.use_protocols: ["udp"]

# Использовать ли принудительно TURN сервер для соединения в видеоконференция
# По умолчанию флаг включен для повышения гарантии установления соединения
#
# Тип данных: булево значение, true\false
jitsi.service.turn.force_relay: true

# Начальный порт для MySQL созданных пространств в приложении.
# Порты начиная с этого будут выделены под MySQL пространств в приложении.
#
# Тип данных: число
# Пример: company.start_port: 35150
company.start_port: 35150

# Конечный порт для MySQL созданных пространств в приложении.
# Порты заканчивая этим будут выделены под MySQL пространств в приложении.
#
# Тип данных: число
# Пример: company.end_port: 35164
company.end_port: 35164

# Необязательный параметр. Sentry DSN ключи для отправки аналитики об ошибках на клиентских платформах
# Ключ необходимо передавать в формате URL, включая протокол
#
# Тип данных: строка
sentry_dsn_key_electron: ""
sentry_dsn_key_android: ""
sentry_dsn_key_ios: ""