# Протокол, по которому производится взаимодействие с прокси сервером.
# Если протокол не указан, прокси сервер не будет использоваться.
# Возможные значения: http, https, socks5, socks5h
#
# Тип данных: строка
# Пример: proxy.protocol: "http"
proxy.protocol: ""

# IP-адрес или доменное имя прокси сервера.
#
# Тип данных: строка
# Пример: proxy.host: "example.com"
proxy.host: ""

# Порт, который слушает прокси сервер.
#
# Тип данных: число
# Пример: proxy.port: 8081
proxy.port: 0

# Имя пользователя для авторизации на прокси сервере.
#
# Необязательный параметр. Используйте его, если прокси сервер требует аутентификацию.
#
# Тип данных: строка
# Пример: proxy.user: "user"
proxy.username: ""

# Пароль для аутентификации на прокси сервере
#
# Необязательный параметр. Используйте его, если прокси сервер требует аутентификацию.
#
# Тип данных: строка
# Пример: proxy.password: "qwerty"
proxy.password: ""