# Метка для сервисов стака
# используется для разделения сервисов между разными стаками
# если используется один стак/сервер, значение должно быть пустой строкой
# Имя должно быть не длиннее 7 символов
#
# Тип данных: строка
# Пример: service_label: "primary"
service_label: ""

# server_id для установки репликации БД между стаками
# основной сервер имеет server_id; резервный server_id основного + 1
# каждый следующий резервный сервер должен иметь server_id, с инкрементом от предыдущего
# если используется один стак/сервер, значение должно быть = 0
#
# Тип данных: число
# Пример: mysql_server_id: 1
mysql_server_id: 0

# Начальный октет для подсети стака
# дефолтное значение = 10
# пример: 172.39.x.0/24 => 172.39.10.0/24
# если поднимается дополнительный стак, start_octet для него должен иметь другое значение от основного, желательно +4 от самого большого
#
# Тип данных: число
# Пример: start_octet: 10
start_octet: 10