# Флаг включения SMS, возможные значения: 1 — включена, 0 — выключена.
# Если SMS включены, то конфигурация как минимум одного провайдера должна быть заполнена.
#
# Значение по умолчанию: 0 — выключено.
# Тип данных: число
# Пример: is_enabled: 0
is_enabled: 0




########################### Настройки SMS-оператора СМС-Агент. ###########################
# Данный оператор является предпочитаемым оператором для рассылки SMS-сообщение на номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания российских номеров необходимо
# указать префикс "+79", для белорусских "+375", а при обслуживании вообще всех номеров только "+".
#
# Тип данных: массив строк
# Пример: sms_agent.provide_phone_code_list: ["+79", "+375"]
sms_agent.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за несколькими провайдерами,
# то система отдаст приоритет тому провайдеру, у которого префикс находится в списке приоритетных.
# Логика ввода значений аналогична логике поля sms_agent.provide_phone_code_list.
# Поле не является обязательным для заполнения
#
# Тип данных: массив строк
# Пример: sms_agent.high_priority_phone_code_list: ["+79"]
sms_agent.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает использоваться для рассылки
# SMS-сообщений. В большинстве случаев стоит оставить небольшой запас, чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
# Пример: sms_agent.min_balance_value: 0
sms_agent.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений. В большинстве случаев
# адрес по умолчанию является актуальными и не требует изменений.
#
# Тип данных: строка
# Пример: sms_agent.provider_gateway_url: example_provider_gateway_url
sms_agent.provider_gateway_url: https://api3.sms-agent.ru/v2.0/

# Имя приложения, используемого при отправке сообщений (для получателя SMS будет являться отправителем).
#
# Тип данных: строка
# Пример: sms_agent.app_name: example_app_name
sms_agent.app_name:

# Логин, который будет использоваться для авторизации в API SMS-провайдера. Логин выдается при оформлении
# договора c SMS-провайдером. В документации подключения провайдера обозначен как login.
#
# Тип данных: строка
# Пример: sms_agent.login: example_login
sms_agent.login:

# Пароль, который будет использоваться для авторизации в API SMS-провайдера. Пароль выдается при оформлении
# договора c SMS-провайдером. В документации подключения провайдера обозначен как password.
#
# Тип данных: строка
# Пример: sms_agent.password: example_password
sms_agent.password:




########################### Настройки SMS-оператора Twilio. ###########################
# Данный оператор может отказаться выполнять рассылку на телефонные номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания номеров казахстана необходимо
# указать префиксы "+796" и "+797", для белорусских "+375", а при обслуживании вообще всех номеров только "+".
#
# Тип данных: массив строк
# Пример: twilio.provide_phone_code_list: ["+796", "+797", "+375"]
twilio.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за несколькими провайдерами,
# то система отдаст приоритет тому провайдеру, у которого префикс находится в списке приоритетных.
# Логика ввода значений аналогична логике поля twilio.provide_phone_code_list.
# Поле не является обязательным для заполнения
#
# Тип данных: массив строк
# Пример: twilio.high_priority_phone_code_list: ["+796", "+797", "+375"]
twilio.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает использоваться для рассылки
# SMS-сообщений. В большинстве случаев стоит оставить небольшой запас, чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
# Пример: twilio.min_balance_value: 0
twilio.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений. В большинстве случаев
# адрес по умолчанию является актуальными и не требует изменений.
# При использовании оператора Twilio поле является обязательным.
#
# Тип данных: строка
# Пример: twilio.provider_gateway_url: example_provider_gateway_url
twilio.provider_gateway_url: https://api.twilio.com/2010-04-01/

# Уникальное имя отправителя. Получатели SMS будут видеть это имя как отправителя сообщения.
# При заполнении данного поля необходимо указать выбранное при подключении провайдера имя.
# В документации подключения провайдера обозначен как Alphanumeric.
#
# Тип данных: строка
# Пример: twilio.app_name: example_app_name
twilio.app_name:

# Идентификатор аккаунта, который будет использоваться для авторизации в API SMS-провайдера.
# Идентификатор выдается при оформлении договора c SMS-провайдером. В документации подключения провайдера
# обозначен как Account SID.
#
# Тип данных: строка
# Пример: twilio.account_sid: example_account_sid
twilio.account_sid:

# Токен, который будет использоваться для авторизации в API SMS-провайдера. Токен выдается при оформлении
# договора c SMS-провайдером. В документации подключения провайдера обозначен как Auth Token.
#
# Тип данных: строка
# Пример: twilio.account_auth_token: example_account_auth_token
twilio.account_auth_token:




########################### Настройки SMS-оператора Vonage. ###########################
# Данный оператор может отказаться выполнять рассылку на телефонные номера РФ.

# Массив обслуживаемых префиксов. Система оперирует номерами в международном формате и
# при выборе оператора опирается на префикс номера. Данный параметр определяет список
# обслуживаемых провайдером префиксов. Например для обслуживания номеров казахстана необходимо
# указать префиксы "+796" и "+797", для белорусских "+375", а при обслуживании вообще всех номеров только "+".
#
# Тип данных: массив строк
# Пример: vonage.provide_phone_code_list: ["+796", "+797", "+375"]
vonage.provide_phone_code_list:

# Массив приоритетных обслуживаемых префиксов. Если один префикс закреплен за несколькими провайдерами,
# то система отдаст приоритет тому провайдеру, у которого префикс находится в списке приоритетных.
# Логика ввода значений аналогична логике поля vonage.provide_phone_code_list.
# Поле не является обязательным для заполнения
#
# Тип данных: массив строк
# Пример: vonage.high_priority_phone_code_list: ["+796", "+797"]
vonage.high_priority_phone_code_list:

# Минимальный уровень баланса на счете оператора, после которого он перестает использоваться для рассылки
# SMS-сообщений. В большинстве случаев стоит оставить небольшой запас, чтобы счет не уходил в минус.
# В качестве валюты используется валюта счета, предоставленного SMS-провайдером.
#
# Тип данных: число
# Пример: vonage.min_balance_value: 0
vonage.min_balance_value:

# Точка входа, куда система будет отправлять API-запросы для рассылки SMS-сообщений. В большинстве случаев
# адрес по умолчанию является актуальными и не требует изменений.
#
# Тип данных: строка
# Пример: vonage.provider_gateway_url: example_provider_gateway_url
vonage.provider_gateway_url: https://rest.nexmo.com/

# Имя приложения, используемого при отправке сообщений (для получателя SMS будет являться отправителем).
#
# Тип данных: строка
# Пример: vonage.app_name: example_app_name
vonage.app_name:

# Ключ, который будет использоваться для авторизации в API SMS-провайдера.
# Ключ выдается при оформлении договора c SMS-провайдером.
# В документации подключения провайдера обозначен как API key.
#
# Тип данных: строка
# Пример: vonage.api_key: example_api_key
vonage.api_key:

# Секрет, который будет использоваться для авторизации в API SMS-провайдера. Секрет выдается при оформлении
# договора c SMS-провайдером. В документации подключения провайдера обозначен как API Secret.
#
# Тип данных: строка
# Пример: vonage.api_secret: example_api_secret
vonage.api_secret: