# Полное имя главного(root) пользователя в приложении.
# С этим именем будет зарегистрирован первый пользователь в приложении.
# Также от имени этого пользователя будут создаваться все новые пространств в приложении.
#
# Тип данных: строка
# Пример: root_user.full_name: Полное Имя
root_user.full_name:

# Номер телефона главного(root) пользователя в приложении.
# С этим номер телефона будет зарегистрирован первый пользователь в приложении.
#
# Тип данных: строка
# Пример: root_user.phone_number: +79220000000
root_user.phone_number:

# Название первой команды
team.init_name: Best Team