# ----------------------------------------------
# ПЕРВЫЙ ЗАПУСК
# ----------------------------------------------

# Полное имя главного (root) пользователя в приложении.
# С этим именем будет зарегистрирован первый пользователь в приложении.
# Также от имени этого пользователя будут создаваться все новые пространств в приложении.
#
# Тип данных: строка, пример: "Полное Имя"
root_user.full_name:

# Номер телефона главного (root) пользователя в приложении.
# С этим номер телефона будет зарегистрирован первый пользователь в приложении.
#
# Тип данных: строка, пример: "+79220000000"
root_user.phone_number:

# Почта и пароль главного (root) пользователя в приложении.
# С этой почтой будет зарегистрирован первый пользователь в приложении.
#
# Тип данных: строка
root_user.mail:
root_user.password:

# Название первой команды.
#
# Тип данных: строка
team.init_name: "First Team"
