# ----------------------------------------------
# ПЕРВЫЙ ЗАПУСК
# ----------------------------------------------

# Полное имя главного (root) пользователя в приложении.
# С этим именем будет зарегистрирован первый пользователь в приложении.
# Также от имени этого пользователя будут создаваться все новые пространств в приложении.
#
# Тип данных: строка, пример: "Полное Имя"
root_user.full_name:

# Номер телефона главного (root) пользователя в приложении.
# С этим номер телефона будет зарегистрирован первый пользователь в приложении.
#
# Тип данных: строка, пример: "+79220000000"
root_user.phone_number:

# Почта и пароль главного (root) пользователя в приложении.
# С этой почтой будет зарегистрирован первый пользователь в приложении.
#
# Тип данных: строка
root_user.mail:
root_user.password:

# Логин используемый для авторизации через SSO по протоколам OpenID Connect или LDAP.
# В поле необходимо указать значение в зависимости от выбранного протокола SSO:
# Для протокола OpenID Connect – почту или номер телефона, используемый при логине
# Для протокола LDAP – username, используемый при логине
#
# Тип данных: строка, пример: "example@mail.example" или "+79220000000" или "ivan_ivanov"
root_user.sso_login:

# Название первой команды.
#
# Тип данных: строка
team.init_name: "Main"

# ----------------------------------------------
# РЕДАКТИРОВАНИЕ ПРОФИЛЯ
# ----------------------------------------------

# Разрешено ли пользователям изменять номер телефона в профиле
profile.phone_change_enabled: true

# Разрешено ли пользователям изменять почтовый адрес в профиле
profile.mail_change_enabled: true

# Разрешено ли пользователям изменять Имя Фамилия в профиле
# Данный параметр не влияет на аутентификацию через SSO/LDAP. Если пользователи
# зарегистрировались через SSO/LDAP, то они не смогут изменить Имя Фамилию в приложении.
profile.name_change_enabled: true

# Разрешено ли пользователям изменять аватар в профиле
profile.avatar_change_enabled: true

# Разрешено ли пользователям изменять бейдж в профиле
profile.badge_change_enabled: true

# Разрешено ли пользователям изменять описание в профиле
profile.description_change_enabled: true

# Разрешено ли пользователям изменять статус в профиле
profile.status_change_enabled: true

# Разрешено ли пользователям удалять свой профиль
profile.deletion_enabled: true

# ----------------------------------------------
# Авторизация перед загрузкой файла
# ----------------------------------------------

# Ограничение доступа к файлам, загруженным в команды, по прямой ссылке. Возможные варианты:
#   — none — проверка не производится, файл всегда доступен по прямой ссылке;
#   — auth — проверка авторизации перед загрузкой — только участник команды может загрузить файл.
file.access_restriction_mode: "none"

# ---------------------------------------
# НАСТРОЙКИ ФАЙЛОВ
# ---------------------------------------
#
# Ограничение размера загружаемых файлов в мегабайтах (диапазон значений от 20 до 2048)
max_file_size_mb: 2048

# Разрешено ли автоматическое удаление файлов с сервера.
# Тип данных: булево значение true/false
file_auto_deletion.is_enabled: false

# Время хранения файлов на сервере перед удалением, если к ним не было обращений от клиентской платформы.
# Обязателен к заполнению в случае включенного параметра file_auto_deletion.is_enabled.
#
# Тип данных: число, пример: 30 – удаление файлов старше 30 дней
file_auto_deletion.file_ttl: 0

# Временной интервал запуска проверки на удаление файлов с сервера.
# Обязателен к заполнению в случае включенного параметра file_auto_deletion_enabled.
#
# Тип данных: число, пример: 2 – интервал каждые 2 дня
file_auto_deletion.check_interval: 0

# Тип удаляемых файлов с сервера.
# Обязателен к заполнению, значение параметра по умолчанию all – удаляются все типы файлов. 
# Его используют для указания типа удаляемого файла или списка типов удаляемых файлов (через запятую), например "audio, voice".
#
# Возможные значения:
# audio – аудиофайлы
# voice – голосовые сообщения
# image – изображения
# video – видео
# archive – архивы (zip, rar, 7z, tar, gz)
# document  – документы (doc, xls, ppt и т.д.)
# file – файлы (прочие, что не является документом или архивом)
#
# Тип данных: строка, пример: "video" – удаление только видео
file_auto_deletion.need_delete_file_type_list: "all"