# ----------------------------------------------
# ПЕРВЫЙ ЗАПУСК
# ----------------------------------------------

# Полное имя главного (root) пользователя в приложении.
# С этим именем будет зарегистрирован первый пользователь в приложении.
# Также от имени этого пользователя будут создаваться все новые пространств в приложении.
#
# Тип данных: строка, пример: "Полное Имя"
root_user.full_name:

# Номер телефона главного (root) пользователя в приложении.
# С этим номер телефона будет зарегистрирован первый пользователь в приложении.
#
# Тип данных: строка, пример: "+79220000000"
root_user.phone_number:

# Почта и пароль главного (root) пользователя в приложении.
# С этой почтой будет зарегистрирован первый пользователь в приложении.
#
# Тип данных: строка
root_user.mail:
root_user.password:

# SSO логин используемый для авторизации через SSO.
# В поле необходимо указать почту или номер телефона, используемый при логине через SSO.
#
# Тип данных: строка, пример: "example@mail.example" или "+79220000000"
root_user.sso_login:

# Название первой команды.
#
# Тип данных: строка
team.init_name: "First Team"

# ----------------------------------------------
# РЕДАКТИРОВАНИЕ ПРОФИЛЯ
# ----------------------------------------------

# Разрешено ли пользователям изменять номер телефона в профиле
profile.phone_change_enabled: true

# Разрешено ли пользователям изменять почтовый адрес в профиле
profile.mail_change_enabled: true

# Разрешено ли пользователям изменять Имя Фамилия в профиле
profile.name_change_enabled: true

# Разрешено ли пользователям изменять аватар в профиле
profile.avatar_change_enabled: true

# Разрешено ли пользователям изменять бейдж в профиле
profile.badge_change_enabled: true

# Разрешено ли пользователям изменять описание в профиле
profile.description_change_enabled: true

# Разрешено ли пользователям изменять статус в профиле
profile.status_change_enabled: true
