import { useAtomValue } from "jotai";
import type { Lang } from "@/api/_types.ts";
import { langState } from "@/api/_stores.ts";

type LangConfig = {
    [K in Lang]?: Record<string, any>;
};

const LANG_CONFIG: LangConfig = {
    ru: {
        no_network_error: "Нет подключения к интернету",
        welcome_page: {
            button: "Начать установку",
            powered_by: "Powered by",
        },
        install_page: {
            header: {
                title: "Compass на сервере Yandex Cloud",
                support_title: "Служба поддержки",
                documentation_title: "Документация",
                support_dialog: {
                    title: "Нужна помощь?",
                    desc: "Напишите нам на support-cloud@getcompass.ru или свяжитесь в мессенджере.",
                    button: "Telegram"
                },
            },
            configure: {
                server_specs_warning: "Сервер не соответствует минимальным требованиям для установки Compass On-premise.\nДля корректной работы измените параметры. Минимальные требования: $VCPU_COUNT vCPU, $RAM_COUNT RAM, $DISK_SIZE SSD.",
                domain_block: {
                    title: "Данные домена",
                    desc: "Для установки необходимо доменное имя, доступное из внешней сети, и доверенный SSL-сертификат.\nУкажите IP-адрес сервера $IP в А-записи поддомена или домена, на котором будет развернут Compass.",
                    checkbox: "Автоматически выпустить SSL-сертификат",
                    checkbox_checked_desc: "Сертификат и ключ будут автоматически выпущены при установке",
                    domain_input_title: "Домен или поддомен",
                    domain_input_placeholder: "sub.domain.com",
                    domain_check_default_error: "Не удалось определить\nIP-адрес домена. Укажите $SERVER_IP в А-записи домена.\n\nЕсли используется внешний proxy, убедитесь, что 80 и 443 порты проксируются на сервер.",
                    domain_check_ip_error: "Привязанный к домену\nIP-адрес $DOMAIN_IP не соответствует IP-адресу сервера. Укажите $SERVER_IP в А-записи домена.\n\nЕсли используется внешний proxy, убедитесь, что 80 и 443 порты проксируются на сервер.",
                    domain_check_close_button: "Хорошо",
                    ssl_upload_button: "Загрузить из файла",
                    ssl_upload_file_placeholder: "Отпустите файл, чтобы загрузить его",
                    ssl_upload_file_error_general: "Не удалось обнаружить необходимые данные в файле. Пожалуйста, выберите другой файл.",
                    ssl_upload_file_error_extension: "Формат файла не поддерживается. Пожалуйста, выберите файл с форматом key, cer, crt, pem или txt.",
                    ssl_upload_file_error_size: "Пожалуйста, загрузите файл не более 10 Мб",
                    ssl_cert_input_title: "SSL-сертификат",
                    ssl_cert_input_placeholder: "-----BEGIN CERTIFICATE-----",
                    ssl_private_key_input_title: "Приватный ключ",
                    ssl_private_key_input_placeholder: "-----BEGIN PRIVATE KEY-----",
                    ssl_cert_upload_button: "Загрузить из файла",
                },
                auth_block: {
                    title: "Авторизация пользователей",
                    desc: "Заполните один или несколько способов авторизации пользователей в приложении.\nПри необходимости вы сможете изменить их после установки.",
                    mail_auth_title: "Авторизация по почте",
                    mail_switcher_title: "Email",
                    mail_host_input_title: "Адрес SMTP-сервера",
                    mail_host_input_placeholder: "Введите адрес",
                    mail_port_input_title: "Порт SMTP-сервера",
                    mail_port_input_placeholder: "Введите порт",
                    mail_login_input_title: "Имя пользователя SMTP",
                    mail_login_input_placeholder: "Введите имя пользователя",
                    mail_password_input_title: "Пароль",
                    mail_password_input_placeholder: "Введите пароль",
                    mail_encryption_title: "Тип шифрования",
                    mail_encryption_none: "Нет",
                    mail_encryption_tls: "TLS",
                    mail_encryption_ssl: "SSL",
                    mail_from_input_title: "Электронный адрес отправителя",
                    mail_from_input_placeholder: "Введите email",
                    sso_auth_title: "Авторизация по SSO",
                    sso_switcher_title: "SSO",
                    sso_provider_oidc: "OpenID",
                    sso_provider_ldap: "LDAP",
                    sso_mapping_subtitle: "Сопоставление атрибутов SSO и полей Compass",
                    sso_mapping_name_input_title: "Имя пользователя",
                    sso_mapping_name_input_placeholder: "Введите название атрибута",
                    sso_mapping_avatar_input_title: "Аватар пользователя",
                    sso_mapping_avatar_input_placeholder: "Введите название атрибута",
                    sso_mapping_badge_input_title: "Бейдж пользователя",
                    sso_mapping_badge_input_placeholder: "Введите название атрибута",
                    sso_mapping_role_input_title: "Должность пользователя",
                    sso_mapping_role_input_placeholder: "Введите название атрибута",
                    sso_mapping_bio_input_title: "Описание пользователя",
                    sso_mapping_bio_input_placeholder: "Введите название атрибута",
                    sso_mapping_mail_input_title: "Электронная почта пользователя",
                    sso_mapping_mail_input_placeholder: "Введите название атрибута",
                    sso_mapping_phone_number_input_title: "Номер телефона пользователя",
                    sso_mapping_phone_number_input_placeholder: "Введите название атрибута",
                    sso_connection_subtitle: "Данные для подключения к SSO серверу",
                    sso_oidc_client_id_input_title: "Client ID",
                    sso_oidc_client_id_input_placeholder: "c6564e06-8660-4107-86b2-043ff87404ec",
                    sso_oidc_client_secret_input_title: "Client Secret",
                    sso_oidc_client_secret_input_placeholder: "Введите секретный ключ",
                    sso_oidc_metadata_link_input_title: "Ссылка на метаданные SSO",
                    sso_oidc_metadata_link_input_placeholder: "Введите ссылку",
                    sso_ldap_host_input_title: "Адрес LDAP-сервера",
                    sso_ldap_host_input_placeholder: "ad.example.com",
                    sso_ldap_port_input_title: "Порт LDAP-сервера",
                    sso_ldap_port_input_placeholder: "636",
                    sso_ldap_use_ssl_checkbox: "LDAP-сервер использует SSL",
                    sso_ldap_cert_strategy_title: "Политика проверки сертификата",
                    sso_ldap_cert_strategy_never: "never",
                    sso_ldap_cert_strategy_allow: "allow",
                    sso_ldap_cert_strategy_try: "try",
                    sso_ldap_cert_strategy_demand: "demand",
                    sso_ldap_user_search_base_input_title: "Каталог для поиска пользователей",
                    sso_ldap_user_search_base_input_placeholder: "ou=users,dc=example,dc=com",
                    sso_ldap_user_unique_attribute_input_title: "Уникальный атрибут учётной записи",
                    sso_ldap_user_unique_attribute_input_placeholder: "uid",
                    sso_ldap_user_search_filter_input_title: "Фильтр для поиска пользователей",
                    sso_ldap_user_search_filter_input_placeholder: "(&(objectClass=person)(uid={0}))",
                    sso_ldap_service_user_subtitle: "Учётная запись для поиска пользователей в LDAP",
                    sso_ldap_user_search_account_dn_input_title: "Полный DN учётной записи",
                    sso_ldap_user_search_account_dn_input_placeholder: "uid=monit,ou=users,dc=example,dc=com",
                    sso_ldap_user_search_account_password_input_title: "Пароль учётной записи",
                    sso_ldap_user_search_account_password_input_placeholder: "Введите пароль",
                    sso_ldap_account_disabling_monitoring_enabled_checkbox: "Мониторинг учётных записей",
                    sms_auth_title: "Авторизация по SMS",
                    sms_sms_agent_switcher_title: "СМС-Агент",
                    sms_sms_agent_from_input_title: "Имя отправителя",
                    sms_sms_agent_from_input_placeholder: "Введите название",
                    sms_sms_agent_login_input_title: "Логин",
                    sms_sms_agent_login_input_placeholder: "Введите логин",
                    sms_sms_agent_password_input_title: "Пароль",
                    sms_sms_agent_password_input_placeholder: "Введите пароль",
                    sms_vonage_switcher_title: "Vonage",
                    sms_vonage_from_input_title: "Имя отправителя",
                    sms_vonage_from_input_placeholder: "Введите название",
                    sms_vonage_api_key_input_title: "API ключ",
                    sms_vonage_api_key_input_placeholder: "Введите ключ",
                    sms_vonage_api_secret_input_title: "API секрет",
                    sms_vonage_api_secret_input_placeholder: "Введите секрет",
                    sms_twilio_switcher_title: "Twilio",
                    sms_twilio_from_input_title: "Имя отправителя",
                    sms_twilio_from_input_placeholder: "Введите название",
                    sms_twilio_account_sid_input_title: "Account SID",
                    sms_twilio_account_sid_input_placeholder: "Введите SID",
                    sms_twilio_auth_token_input_title: "Auth Token",
                    sms_twilio_auth_token_input_placeholder: "Введите токен",
                },
                admin_block: {
                    title: "Данные администратора",
                    desc: "Заполните данные для авторизации администратора в приложении и название первого рабочего пространства. После установки вы сможете создать дополнительные рабочие пространства.",
                    admin_title: "Данные",
                    admin_name_input_title: "Имя Фамилия",
                    admin_name_input_placeholder: "Иван Петров",
                    space_name_input_title: "Название первого пространства",
                    space_name_input_placeholder: "Введите название",
                    admin_creds_need_select_auth_method: "Выберите минимум один способ авторизации пользователей на сервере",
                    admin_creds_title: "Доступ администратора",
                    admin_sso_login_input_title: "Логин в SSO",
                    admin_sso_login_input_placeholder: "admin",
                    admin_phone_number_input_title: "Телефон",
                    admin_phone_number_input_placeholder: "Введите телефон",
                    admin_email_mail_input_title: "Email",
                    admin_email_mail_input_placeholder: "hello@your-domain.ru",
                    admin_email_password_input_title: "Пароль",
                    admin_email_password_input_placeholder: "Введите пароль (от 8 до 40 символов)",
                    admin_email_password_input_error: "Пароль должен содержать\nот 8 до 40 символов",
                },
                confirm_block: {
                    domain_title: "Домен",
                    auth_title: "Авторизация",
                    admin_title: "Администратор",
                    offer_desc: "Я согласен с условиями политики конфиденциальности и публичной оферты на право использования ПО Compass в Yandex Cloud",
                    install_button: "Установить",
                },
            },
            install_in_progress: {
                install_title: "Устанавливаем приложение",
                activate_title: "Активируем сервер",
                desc: "Обычно установка занимает 7-10 минут",
            },
            install_success: {
                title: "Установка завершена",
                desc: `Перейдите на сайт $DOMAIN, чтобы начать работу.`,
                admin_phone_number_title: "Телефон главного администратора",
                admin_mail_login_title: "Электронная почта главного администратора",
                admin_mail_password_title: "Пароль",
                admin_sso_login_title: "Логин главного администратора в SSO",
                button: "Начать работу",
            },
            install_failed: {
                error_install_title: "Ошибка установки",
                error_server_activate_title: "Ошибка активации сервера",
                desc: "Обычно установка занимает 7-10 минут",
                back_to_configure_button: "Вернуться к конфигурации",
                download_logs_dialog: {
                    title: "Логи установки",
                    desc: "Рекомендуем скачать файл с логами установки перед возвращением к конфигурации.",
                    download_logs_button: "Скачать логи",
                    no_need_download_logs_button: "Не скачивать"
                },
                retry_activate_server_button: "Повторить активацию",
                download_logs_button: "Скачать логи",
            },
            hints: {
                lets_encrypt_checkbox: "Вы можете использовать собственный сертификат или автоматически выпустить бесплатный доверенный сертификат от Let’s Encrypt. Сертификат Let’s Encrypt автоматически продлевается каждые 30 дней.",
                domain_input_pt1: "Для установки Compass On-premise требуется публично-доступное доменное имя, которое ведет на сервер. Перед установкой укажите в А-записи домена IP-адрес сервера. Узнать\nIP-адрес можно в консоли Yandex Cloud.",
                domain_input_pt2: "Если вы регистрируете новый домен, до момента его доступности может пройти до 48 часов. Убедитесь, что домен ведёт на сервер перед запуском установки.",
                ssl_certificate_input: "Для корректной работы клиентских приложений необходимо использовать сертификат с полной цепочкой.",
                private_key_input: "Укажите приватный ключ, относящийся к выбранному сертификату.",
                mail_block_title: "Вы можете настроить отправку писем через собственный SMTP-сервер, либо воспользоваться одним из публичных почтовых сервисов. Ознакомьтесь с инструкциями по настройке в нашей официальной документации:",
                mail_block_title_link_gmail: "Подключение почты Gmail;",
                mail_block_title_link_yandex: "Подключение почты Яндекс.",
                mail_title: "Параметры имени пользователя и пароля могут быть не заполнены, если SMTP-сервер работает без аутентификации. Порт по умолчанию при использовании шифрования TLS или SSL: 465, при использовании без шифрования: 25.",
                sso_block_title: "Compass поддерживает авторизацию пользователей через Single Sign-On по протоколам OpenID Connect или LDAP.",
                sso_title_pt1: "Если вы планируете использовать протокол OpenID Connect, ознакомьтесь с инструкциями в нашей официальной документации по ссылкам:",
                sso_title_link_adfs: "Active Directory Federation Services (AD FS);",
                sso_title_link_okta: "Okta;",
                sso_title_link_keycloak: "Keycloak.",
                sso_title_pt2: "Если вы планируете использовать протокол LDAP, ознакомьтесь с инструкцией.",
                sso_mapping_attributes_subtitle_pt1: "Заполните параметры для автоматической подгрузки информации о пользователе при регистрации через SSO. Поля Имя, Электронная почта и Номер пользователя обязательны к заполнению, остальные поля могут быть пустыми, если атрибут не требуется. Поля электронной почты и номера телефона необходимы для корректной первой авторизации администратора в Compass.",
                sso_mapping_attributes_subtitle_pt2: "Атрибуты, которые требуется подтягивать из SSO по протоколу OIDC, обязательно указываются в фигурных скобках. Например, для имени пользователя в Compass атрибут можно указать следующим образом: {first_name}.",
                sso_mapping_attributes_subtitle_pt3: "Если требуется указать несколько атрибутов, они указываются в фигурных скобках по отдельности. Например: {first_name} {last_name}.",
                sso_connect_subtitle: "Ознакомиться с инструкциями для получения данных подключения к SSO-серверу можно по ссылкам:",
                sso_connect_subtitle_adfs: "Active Directory Federation Services (AD FS);",
                sso_connect_subtitle_okta: "Okta;",
                sso_connect_subtitle_keycloak: "Keycloak.",
                ldap_connect_subtitle: "Ознакомиться с инструкцией для получения данных подключения к SSO-серверу можно по ссылке.",
                ldap_require_cert_strategy_subtitle: "Стратегия проверки сертификатов при установке безопасного соединения с LDAP-сервером.\nВозможные значения:",
                ldap_require_cert_strategy_subtitle_never: "never – проверка сертификата отключена;",
                ldap_require_cert_strategy_subtitle_allow: "allow – проверка сертификата выполняется, но клиент всё равно разрешает подключение в случае неудачной валидации;",
                ldap_require_cert_strategy_subtitle_try: "try – сертификат запрашивается, если он не предоставлен, сессия продолжается нормально. Если сертификат предоставлен, но не может быть проверен, сессия немедленно прерывается;",
                ldap_require_cert_strategy_subtitle_demand: "demand – требует обязательной проверки сертификата сервера. Соединение не будет установлено, если сертификат не прошёл проверку.",
                ldap_search_account_subtitle: "Указанная учётная запись LDAP будет использоваться для поиска других учётных записей в каталоге для их мониторинга.",
                ldap_search_account_dn_input: "Distinguished Name учётной записи LDAP, которая будет использоваться для поиска других учётных записей в каталоге.",
                ldap_monitoring_checkbox: "Включён ли мониторинг удаления / блокировки учётной записи в каталоге LDAP для запуска автоматической блокировки связанного с ней пользователя в Compass. Вы сможете настроить уровни блокировки и интервал проверок после установки.",
                sms_block_title: "Для авторизации пользователей по номеру телефона необходимо зарегистрировать личный кабинет на сайте одного из перечисленных поставщиков услуг доставки SMS и получить данные для авторизации.",
                sms_agent_title: "С инструкцией для подключения провайдера СМС-Агент можно ознакомиться по ссылке.",
                vonage_title: "С инструкцией для подключения провайдера Vonage можно ознакомиться по ссылке.",
                twilio_title: "С инструкцией для подключения провайдера Twilio можно ознакомиться по ссылке.",
                admin_profile_creds_title: "Администратор является первым пользователем приложения. От его имени будут создаваться новые рабочие пространства. При необходимости вы сможете изменить имя пользователя и название пространства в приложении после установки.",
                admin_auth_creds_title: "Заполните данные, которые будут использоваться для аутентификации администратора в приложении. Почту, пароль и номер телефона при необходимости можно будет изменить в приложении после установки.",
            },
        },
    },
    en: {},
    de: {},
    fr: {},
    es: {},
    it: {},
};

export function useLangString() {
    const lang = useAtomValue(langState);

    const getValueFromConfig = (keys: string[], config: any): string | undefined => {
        if (!keys.length || typeof config !== "object") {
            return config;
        }

        const [ nextKey, ...rest ] = keys;
        return getValueFromConfig(rest, config[nextKey]);
    };

    return (key: string): string => {
        let result = getValueFromConfig(key.split("."), LANG_CONFIG[lang]);
        if (result === undefined) {
            result = getValueFromConfig(key.split("."), LANG_CONFIG["ru"]);
        }
        return result || "";
    };
}
